[target.loongarch64-unknown-linux-gnu]
# Use a cross image that includes LoongArch toolchains
image = "messense/cross:loongarch64-unknown-linux-gnu"

[target.i686-unknown-linux-gnu]
image = "ghcr.io/cross-rs/i686-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"